### ISSUE TITLE
Telnet Acces error in Linux

### ISSUE THREAD

**Issue by CharlyBote** [ShaneMcC/phprouter#23]
Hi..
I try to access to a device via telnet, but I receive the following error

[Sun Sep 05 23:28:54.434233 2021] [php7:warn] [pid 7033] [client 192.168.11.200:49671] PHP Warning: array_key_exists() expects parameter 2 to be array, null given in /var/www/buscacli/thirdparty/net_telnet/Net/Telnet.php on line 100
[Sun Sep 05 23:28:54.434277 2021] [php7:error] [pid 7033] [client 192.168.11.200:49671] PHP Fatal error: Uncaught Exception: unknown TELNET command: 253 in /var/www/buscacli/thirdparty/net_telnet/Net/Telnet.php:768\nStack trace:\n#0 /var/www/buscacli/thirdparty/net_telnet/Net/Telnet.php(738): Net_Telnet->send_telcmd('\xFD', '\x01')\n#1 /var/www/buscacli/thirdparty/net_telnet/Net/Telnet.php(642): Net_Telnet->initial_options()\n#2 /var/www/buscacli/Sockets/TelnetSocket.php(27): Net_Telnet->connect()\n#3 /var/www/buscacli/Implementations/CiscoTrait.php(33): shanemcc\PhpRouter\Sockets\TelnetSocket->connect()\n#4 /var/www/buscacli/test.php(9): shanemcc\PhpRouter\Implementations\CiscoRouter->connect()\n#5 {main}\n thrown in /var/www/buscacli/thirdparty/net_telnet/Net/Telnet.php on line 768.

**Comment by iraqhub** [comment]
same error here

**Comment by ShaneMcC** [comment]
Hi,

Project isn't dead, but I've not encountered this error myself as I don't currently use this with any telnet-only devices. If you can provide more information about how to reproduce (ie, what are you actually connecting to device-wise and what are you attempting to do?)

Alternatively, for many reasons, I'd suggest switching to accessing the devices via SSH not Telnet.
